version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    groups:
      eslint:
        patterns:
          - "eslint*"
    ignore:
      - dependency-name: "eslint"
        versions: [">= 8"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
